FROM kartoza/geoserver:geonode-2.23.0.x

COPY /config.yaml /usr/local/tomcat/webapps/geoserver/data/printing/config.yaml
COPY /WAPP_logo.png /usr/local/tomcat/webapps/geoserver/data/printing/WAPP_logo.png
WORKDIR /usr/local/tomcat/webapps/geoserver/
